# Generated by Django 5.0.14 on 2026-02-25 22:00

import django.contrib.auth.models
import django.contrib.auth.validators
import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre completo de la organización", max_length=255
                    ),
                ),
                (
                    "org_type",
                    models.CharField(
                        choices=[
                            ("FIRE_DEPT", "Cuerpo de Bomberos"),
                            ("POLICE", "Policía"),
                            ("RESCUE", "Equipo de Rescate"),
                            ("MEDICAL", "Servicios Médicos"),
                            ("OTHER", "Otro"),
                        ],
                        default="OTHER",
                        help_text="Tipo de organización de emergencias",
                        max_length=20,
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True,
                        help_text="Email de contacto general",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True,
                        help_text="Teléfono de contacto general",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True,
                        help_text="Dirección física de la organización",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si la organización está activa en el sistema",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Organización",
                "verbose_name_plural": "Organizaciones",
                "db_table": "organizations",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "users",
                "ordering": ["-created_at"],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Incident",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "incident_type",
                    models.CharField(
                        choices=[
                            ("WILDFIRE", "Incendio Forestal"),
                            ("SEARCH", "Búsqueda de Persona"),
                            ("RESCUE", "Rescate"),
                            ("MEDICAL", "Emergencia Médica"),
                            ("NATURAL_DISASTER", "Desastre Natural"),
                            ("OTHER", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Abierto"),
                            ("CLOSED", "Cerrado"),
                            ("TRIAGE", "En Evaluación"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True,
                        help_text="Ubicación GPS principal del incidente (WGS84)",
                        null=True,
                        srid=4326,
                    ),
                ),
                ("location_address", models.TextField(blank=True, null=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Usuario que creó este incidente",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_incidents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "incidents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IncidentMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role_in_incident",
                    models.CharField(
                        choices=[
                            ("SUPERVISOR", "Supervisor"),
                            ("OPERATIVE", "Operativo"),
                            ("SUPPORT", "Apoyo"),
                        ],
                        default="OPERATIVE",
                        help_text="Rol específico del usuario dentro de este incidente",
                        max_length=20,
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Fecha de incorporación al incidente",
                    ),
                ),
                (
                    "left_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha de salida del incidente (null si aún está activo)",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si el usuario sigue activo en el incidente",
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        help_text="Incidente en el que participa el usuario",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incident_members",
                        to="core.incident",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Usuario que participa en el incidente",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incident_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Miembro de incidente",
                "verbose_name_plural": "Miembros de incidentes",
                "db_table": "incident_members",
                "ordering": ["-joined_at"],
                "unique_together": {("incident", "user")},
            },
        ),
        migrations.AddField(
            model_name="incident",
            name="members",
            field=models.ManyToManyField(
                help_text="Usuarios asignados a este incidente",
                related_name="incidents",
                through="core.IncidentMember",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="incident",
            name="owner_organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organización responsable del incidente",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="incidents",
                to="core.organization",
            ),
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Administrador"),
                            ("SUPERVISOR", "Supervisor"),
                            ("OPERATIVE", "Operativo"),
                        ],
                        default="OPERATIVE",
                        help_text="Rol del usuario en el sistema",
                        max_length=20,
                    ),
                ),
                (
                    "emergency_contact",
                    models.CharField(
                        blank=True,
                        help_text="Nombre del contacto de emergencia",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "emergency_phone",
                    models.CharField(
                        blank=True,
                        help_text="Teléfono del contacto de emergencia",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "medical_notes",
                    models.TextField(
                        blank=True,
                        help_text="Información médica relevante (alergias, condiciones, etc.)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organización a la que pertenece el usuario",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="members",
                        to="core.organization",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Usuario al que pertenece este perfil",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil",
                "verbose_name_plural": "Perfiles",
                "db_table": "profiles",
            },
        ),
        migrations.CreateModel(
            name="WorkArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "area_type",
                    models.CharField(
                        choices=[("CIRCLE", "Circle"), ("POLYGON", "Polygon")],
                        max_length=10,
                    ),
                ),
                (
                    "center",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("radius_m", models.FloatField(blank=True, null=True)),
                (
                    "polygon",
                    django.contrib.gis.db.models.fields.PolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_areas",
                        to="core.incident",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "fcm_token",
                    models.TextField(
                        help_text="Token de Firebase Cloud Messaging para notificaciones push"
                    ),
                ),
                (
                    "device_name",
                    models.CharField(
                        blank=True,
                        help_text="Nombre descriptivo del dispositivo (ej: 'iPhone de Juan')",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("IOS", "iOS"),
                            ("ANDROID", "Android"),
                            ("WEB", "Web"),
                        ],
                        help_text="Plataforma del dispositivo",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si el dispositivo puede recibir notificaciones",
                    ),
                ),
                ("last_used", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Usuario al que pertenece este dispositivo",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Dispositivo",
                "verbose_name_plural": "Dispositivos",
                "db_table": "devices",
                "unique_together": {("user", "fcm_token")},
            },
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("SOS", "SOS Emergencia"),
                            ("MAN_DOWN", "Operativo Caído"),
                            ("LOST", "Operativo Perdido/Desorientado"),
                            ("GEOFENCE", "Fuera de Zona Segura"),
                            ("ANOMALY", "Anomalía Detectada"),
                            ("OTHER", "Otro"),
                        ],
                        help_text="Tipo de emergencia reportada",
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.IntegerField(
                        default=3,
                        help_text="Nivel de gravedad: 1=Crítico, 5=Informativo",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Abierta"),
                            ("ACK", "Reconocida"),
                            ("CLOSED", "Cerrada"),
                        ],
                        default="OPEN",
                        help_text="Estado actual de la alerta",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        help_text="Ubicación GPS donde se generó la alerta (WGS84)",
                        srid=4326,
                    ),
                ),
                ("acked_at", models.DateTimeField(blank=True, null=True)),
                ("ack_notes", models.TextField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("close_notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "acked_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que reconoció la alerta",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acked_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que cerró la alerta",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="closed_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Usuario que generó esta alerta",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        blank=True,
                        help_text="Incidente relacionado con esta alerta (opcional)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="core.incident",
                    ),
                ),
            ],
            options={
                "db_table": "alerts",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["incident", "status"], name="alerts_inciden_9cc88e_idx"
                    ),
                    models.Index(fields=["status"], name="alerts_status_0e4dc1_idx"),
                    models.Index(
                        fields=["alert_type"], name="alerts_alert_t_eda531_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="alerts_created_965da5_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RiskCell",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "cell",
                    django.contrib.gis.db.models.fields.PolygonField(
                        help_text="Área geográfica representada como polígono",
                        srid=4326,
                    ),
                ),
                (
                    "trackpoint_count",
                    models.IntegerField(
                        default=0,
                        help_text="Número de puntos de tracking en esta celda",
                    ),
                ),
                (
                    "alert_count",
                    models.IntegerField(
                        default=0, help_text="Número de alertas en esta celda"
                    ),
                ),
                (
                    "risk_score",
                    models.FloatField(
                        default=0,
                        help_text="Puntuación de riesgo entre 0 y 100",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "last_activity",
                    models.DateTimeField(
                        help_text="Última vez que se registró actividad en esta celda"
                    ),
                ),
                (
                    "calculated_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Momento en que se calculó el riesgo",
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        help_text="Incidente al que pertenece esta celda de riesgo",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_cells",
                        to="core.incident",
                    ),
                ),
            ],
            options={
                "verbose_name": "Celda de riesgo",
                "verbose_name_plural": "Celdas de riesgo",
                "db_table": "risk_cells",
                "ordering": ["-risk_score"],
                "indexes": [
                    models.Index(
                        fields=["incident", "risk_score"],
                        name="risk_cells_inciden_d8770d_idx",
                    ),
                    models.Index(
                        fields=["risk_score"], name="risk_cells_risk_sc_bf5790_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TrackPoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        help_text="Coordenadas GPS (longitud, latitud) en sistema WGS84",
                        srid=4326,
                    ),
                ),
                (
                    "accuracy_m",
                    models.FloatField(
                        blank=True,
                        help_text="Precisión estimada del GPS en metros",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "altitude",
                    models.FloatField(
                        blank=True,
                        help_text="Altitud en metros sobre el nivel del mar",
                        null=True,
                    ),
                ),
                (
                    "speed",
                    models.FloatField(
                        blank=True,
                        help_text="Velocidad en metros por segundo",
                        null=True,
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(
                        help_text="Momento en que el GPS registró la posición"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Momento en que se recibió en el servidor",
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        blank=True,
                        help_text="Incidente asociado (opcional)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="track_points",
                        to="core.incident",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Usuario que registró esta posición",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="track_points",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Punto de rastreo",
                "verbose_name_plural": "Puntos de rastreo",
                "db_table": "track_points",
                "ordering": ["-recorded_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "recorded_at"],
                        name="track_point_user_id_23ea10_idx",
                    ),
                    models.Index(
                        fields=["incident", "recorded_at"],
                        name="track_point_inciden_932f6c_idx",
                    ),
                    models.Index(
                        fields=["recorded_at"], name="track_point_recorde_221278_idx"
                    ),
                ],
            },
        ),
    ]
