# Generated by Django 5.0.14 on 2026-02-26 22:20

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organizacion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre completo de la organización", max_length=255
                    ),
                ),
                (
                    "org_type",
                    models.CharField(
                        choices=[
                            ("FIRE_DEPT", "Cuerpo de Bomberos"),
                            ("POLICE", "Policía"),
                            ("RESCUE", "Equipo de Rescate"),
                            ("MEDICAL", "Servicios Médicos"),
                            ("OTHER", "Otro"),
                        ],
                        default="OTHER",
                        help_text="Tipo de organización de emergencias",
                        max_length=20,
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True,
                        help_text="Email de contacto general",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True,
                        help_text="Teléfono de contacto general",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True,
                        help_text="Dirección física de la organización",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si la organización está activa en el sistema",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Organización",
                "verbose_name_plural": "Organizaciones",
                "db_table": "organizaciones",
                "ordering": ["name"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="device",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="device",
            name="user",
        ),
        migrations.RemoveField(
            model_name="incident",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="incident",
            name="members",
        ),
        migrations.RemoveField(
            model_name="incident",
            name="owner_organization",
        ),
        migrations.RemoveField(
            model_name="workarea",
            name="incident",
        ),
        migrations.RemoveField(
            model_name="riskcell",
            name="incident",
        ),
        migrations.RemoveField(
            model_name="trackpoint",
            name="incident",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="user",
        ),
        migrations.RemoveField(
            model_name="trackpoint",
            name="user",
        ),
        migrations.CreateModel(
            name="Dispositivo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "fcm_token",
                    models.TextField(
                        help_text="Token de Firebase Cloud Messaging para notificaciones push"
                    ),
                ),
                (
                    "device_name",
                    models.CharField(
                        blank=True,
                        help_text="Nombre descriptivo del dispositivo (ej: 'iPhone de Juan')",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("IOS", "iOS"),
                            ("ANDROID", "Android"),
                            ("WEB", "Web"),
                        ],
                        help_text="Plataforma del dispositivo",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si el dispositivo puede recibir notificaciones",
                    ),
                ),
                ("last_used", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Usuario al que pertenece este dispositivo",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Dispositivo",
                "verbose_name_plural": "Dispositivos",
                "db_table": "dispositivos",
                "unique_together": {("user", "fcm_token")},
            },
        ),
        migrations.CreateModel(
            name="Incidente",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "incident_type",
                    models.CharField(
                        choices=[
                            ("WILDFIRE", "Incendio Forestal"),
                            ("SEARCH", "Búsqueda de Persona"),
                            ("RESCUE", "Rescate"),
                            ("MEDICAL", "Emergencia Médica"),
                            ("NATURAL_DISASTER", "Desastre Natural"),
                            ("OTHER", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Abierto"),
                            ("CLOSED", "Cerrado"),
                            ("TRIAGE", "En Evaluación"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True,
                        help_text="Ubicación GPS principal del incidente (WGS84)",
                        null=True,
                        srid=4326,
                    ),
                ),
                ("location_address", models.TextField(blank=True, null=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Usuario que creó este incidente",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_incidents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        help_text="Usuarios asignados a este incidente",
                        related_name="incidents",
                        through="core.IncidentMember",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner_organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organización responsable del incidente",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incidents",
                        to="core.organizacion",
                    ),
                ),
            ],
            options={
                "db_table": "incidentes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CeldaRiesgo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "cell",
                    django.contrib.gis.db.models.fields.PolygonField(
                        help_text="Área geográfica representada como polígono",
                        srid=4326,
                    ),
                ),
                (
                    "trackpoint_count",
                    models.IntegerField(
                        default=0,
                        help_text="Número de puntos de tracking en esta celda",
                    ),
                ),
                (
                    "alert_count",
                    models.IntegerField(
                        default=0, help_text="Número de alertas en esta celda"
                    ),
                ),
                (
                    "risk_score",
                    models.FloatField(
                        default=0,
                        help_text="Puntuación de riesgo entre 0 y 100",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "last_activity",
                    models.DateTimeField(
                        help_text="Última vez que se registró actividad en esta celda"
                    ),
                ),
                (
                    "calculated_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Momento en que se calculó el riesgo",
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        help_text="Incidente al que pertenece esta celda de riesgo",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_cells",
                        to="core.incidente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Celda de riesgo",
                "verbose_name_plural": "Celdas de riesgo",
                "db_table": "celdas_riesgo",
                "ordering": ["-risk_score"],
            },
        ),
        migrations.CreateModel(
            name="AreaTrabajo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "area_type",
                    models.CharField(
                        choices=[("CIRCLE", "Circle"), ("POLYGON", "Polygon")],
                        max_length=10,
                    ),
                ),
                (
                    "center",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("radius_m", models.FloatField(blank=True, null=True)),
                (
                    "polygon",
                    django.contrib.gis.db.models.fields.PolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_areas",
                        to="core.incidente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Alerta",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("SOS", "SOS Emergencia"),
                            ("MAN_DOWN", "Operativo Caído"),
                            ("LOST", "Operativo Perdido/Desorientado"),
                            ("GEOFENCE", "Fuera de Zona Segura"),
                            ("ANOMALY", "Anomalía Detectada"),
                            ("OTHER", "Otro"),
                        ],
                        help_text="Tipo de emergencia reportada",
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.IntegerField(
                        default=3,
                        help_text="Nivel de gravedad: 1=Crítico, 5=Informativo",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Abierta"),
                            ("ACK", "Reconocida"),
                            ("CLOSED", "Cerrada"),
                        ],
                        default="OPEN",
                        help_text="Estado actual de la alerta",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        help_text="Ubicación GPS donde se generó la alerta (WGS84)",
                        srid=4326,
                    ),
                ),
                ("acked_at", models.DateTimeField(blank=True, null=True)),
                ("ack_notes", models.TextField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("close_notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "acked_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que reconoció la alerta",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acked_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que cerró la alerta",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="closed_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Usuario que generó esta alerta",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        blank=True,
                        help_text="Incidente relacionado con esta alerta (opcional)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="core.incidente",
                    ),
                ),
            ],
            options={
                "db_table": "alertas",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterField(
            model_name="incidentmember",
            name="incident",
            field=models.ForeignKey(
                help_text="Incidente en el que participa el usuario",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incident_members",
                to="core.incidente",
            ),
        ),
        migrations.CreateModel(
            name="Perfil",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Administrador"),
                            ("SUPERVISOR", "Supervisor"),
                            ("OPERATIVE", "Operativo"),
                        ],
                        default="OPERATIVE",
                        help_text="Rol del usuario en el sistema",
                        max_length=20,
                    ),
                ),
                (
                    "emergency_contact",
                    models.CharField(
                        blank=True,
                        help_text="Nombre del contacto de emergencia",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "emergency_phone",
                    models.CharField(
                        blank=True,
                        help_text="Teléfono del contacto de emergencia",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "medical_notes",
                    models.TextField(
                        blank=True,
                        help_text="Información médica relevante (alergias, condiciones, etc.)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organización a la que pertenece el usuario",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="members",
                        to="core.organizacion",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Usuario al que pertenece este perfil",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil",
                "verbose_name_plural": "Perfiles",
                "db_table": "profiles",
            },
        ),
        migrations.CreateModel(
            name="PuntoRastreo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        help_text="Coordenadas GPS (longitud, latitud) en sistema WGS84",
                        srid=4326,
                    ),
                ),
                (
                    "accuracy_m",
                    models.FloatField(
                        blank=True,
                        help_text="Precisión estimada del GPS en metros",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "altitude",
                    models.FloatField(
                        blank=True,
                        help_text="Altitud en metros sobre el nivel del mar",
                        null=True,
                    ),
                ),
                (
                    "speed",
                    models.FloatField(
                        blank=True,
                        help_text="Velocidad en metros por segundo",
                        null=True,
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(
                        help_text="Momento en que el GPS registró la posición"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Momento en que se recibió en el servidor",
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        blank=True,
                        help_text="Incidente asociado (opcional)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="track_points",
                        to="core.incidente",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Usuario que registró esta posición",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="track_points",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Punto de rastreo",
                "verbose_name_plural": "Puntos de rastreo",
                "db_table": "puntos_rastreo",
                "ordering": ["-recorded_at"],
            },
        ),
        migrations.DeleteModel(
            name="Alert",
        ),
        migrations.DeleteModel(
            name="Device",
        ),
        migrations.DeleteModel(
            name="WorkArea",
        ),
        migrations.DeleteModel(
            name="RiskCell",
        ),
        migrations.DeleteModel(
            name="Organization",
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
        migrations.DeleteModel(
            name="TrackPoint",
        ),
        migrations.AddIndex(
            model_name="celdariesgo",
            index=models.Index(
                fields=["incident", "risk_score"], name="celdas_ries_inciden_5ecb67_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="celdariesgo",
            index=models.Index(
                fields=["risk_score"], name="celdas_ries_risk_sc_756595_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alerta",
            index=models.Index(
                fields=["incident", "status"], name="alertas_inciden_5b220c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alerta",
            index=models.Index(fields=["status"], name="alertas_status_1df234_idx"),
        ),
        migrations.AddIndex(
            model_name="alerta",
            index=models.Index(
                fields=["alert_type"], name="alertas_alert_t_cdcd39_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alerta",
            index=models.Index(
                fields=["created_at"], name="alertas_created_f501d6_idx"
            ),
        ),
        migrations.DeleteModel(
            name="Incident",
        ),
        migrations.AddIndex(
            model_name="puntorastreo",
            index=models.Index(
                fields=["user", "recorded_at"], name="puntos_rast_user_id_0ae917_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="puntorastreo",
            index=models.Index(
                fields=["incident", "recorded_at"],
                name="puntos_rast_inciden_f48287_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="puntorastreo",
            index=models.Index(
                fields=["recorded_at"], name="puntos_rast_recorde_3fb79c_idx"
            ),
        ),
    ]
