# Generated by Django 5.0.14 on 2026-02-26 22:47

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_organizacion_alter_device_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RiskReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        help_text="Ubicación del riesgo (coordenadas GPS)", srid=4326
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Descripción del riesgo observado"),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Bajo"),
                            ("MEDIUM", "Medio"),
                            ("HIGH", "Alto"),
                        ],
                        default="MEDIUM",
                        help_text="Nivel de severidad del riesgo",
                        max_length=10,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Si el reporte sigue vigente"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Fecha de creación del reporte"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Última actualización"
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        help_text="Incidente al que pertenece el reporte",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_reports",
                        to="core.incidente",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        help_text="Usuario que reporta el riesgo",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Reporte de Riesgo",
                "verbose_name_plural": "Reportes de Riesgo",
                "db_table": "risk_reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="CeldaRiesgo",
        ),
    ]
