# Generated by Django 5.0.14 on 2026-03-16 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sync_profile_name_lastname'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterModelTable(name='alerta', table='alerts'),
                migrations.AlterModelTable(name='dispositivo', table='devices'),
                migrations.AlterModelTable(name='incidente', table='incidents'),
                migrations.AlterModelTable(name='organizacion', table='organizations'),
                migrations.AlterModelTable(name='puntorastreo', table='track_points'),
            ],
        ),
        migrations.AddField(
            model_name='perfil',
            name='assigned_supervisor',
            field=models.ForeignKey(blank=True, help_text='Supervisor asignado al usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='perfil',
            name='avatar',
            field=models.FileField(blank=True, help_text='Imagen de avatar del usuario', null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Fecha de nacimiento del usuario', null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='blood_type',
            field=models.CharField(blank=True, help_text='Grupo sanguineo', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='city',
            field=models.CharField(blank=True, help_text='Ciudad del usuario', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='country',
            field=models.CharField(blank=True, help_text='Pais del usuario', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='device',
            field=models.ForeignKey(blank=True, help_text='Dispositivo asignado al usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_profiles', to='core.dispositivo'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='dni',
            field=models.CharField(blank=True, help_text='Documento nacional de identidad', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='language',
            field=models.CharField(blank=True, help_text='Idioma preferido del usuario', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='operative_schedule',
            field=models.CharField(blank=True, help_text='Horario operativo del usuario', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='province',
            field=models.CharField(blank=True, help_text='Provincia del usuario', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='specialties',
            field=models.JSONField(blank=True, default=list, help_text='Especialidades operativas del usuario'),
        ),
        migrations.RunSQL(
            sql=(
                "UPDATE profiles "
                "SET medical_notes = '[]' "
                "WHERE medical_notes IS NULL OR BTRIM(medical_notes) = '';"
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql=(
                "UPDATE profiles "
                "SET medical_notes = TO_JSON(ARRAY[medical_notes])::text "
                "WHERE medical_notes IS NOT NULL AND BTRIM(medical_notes) <> '';"
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='perfil',
            name='emergency_phone',
            field=models.CharField(blank=True, help_text='Telefono del contacto de emergencia', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='medical_notes',
            field=models.JSONField(blank=True, default=list, help_text='Informacion medica relevante'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organizacion a la que pertenece el usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='core.organizacion'),
        ),
    ]
