# Generated by Django 5.0.14 on 2026-03-16 22:35

import django.contrib.gis.db.models.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_perfil_assigned_supervisor_perfil_avatar_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LightningStrike",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        help_text="Ubicación GPS del rayo (latitud, longitud)",
                        srid=4326,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        help_text="Fecha y hora de detección del rayo"
                    ),
                ),
                (
                    "intensity",
                    models.FloatField(
                        blank=True,
                        help_text="Intensidad del rayo en kiloamperios (kA)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Rayo",
                "verbose_name_plural": "Rayos",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["timestamp"], name="core_lightn_timesta_acae41_idx"
                    ),
                    models.Index(
                        fields=["location"], name="core_lightn_locatio_4e4918_idx"
                    ),
                ],
            },
        ),
    ]
