# Generated by Django 5.0.14 on 2026-03-17 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_lightningstrike"),
        ("core", "0010_organizacion_location"),
    ]

    operations = []
