# Generated by Django 5.0.14 on 2026-03-20 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_codigoresetpassword'),
        ('core', '0011_merge_0008_lightningstrike_0010_organizacion_location'),
    ]

    operations = [
    ]
