# Generated by Django 5.0.14 on 2026-03-20 09:30

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_merge_20260320_1030'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='codigoresetpassword',
            new_name='password_re_email_e60f2a_idx',
            old_name='password_re_email_0c2b89_idx',
        ),
        migrations.RenameIndex(
            model_name='codigoresetpassword',
            new_name='password_re_expira__785e21_idx',
            old_name='password_re_expira__624020_idx',
        ),
        migrations.RemoveField(
            model_name='organizacion',
            name='location',
        ),
        migrations.AddField(
            model_name='perfil',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Ubicacion geografica del usuario (latitud, longitud)', null=True, srid=4326),
        ),
    ]
