# Generated by Django 5.0.14 on 2026-03-21 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_merge_20260319_2230"),
        (
            "core",
            "0013_rename_password_re_email_0c2b89_idx_password_re_email_e60f2a_idx_and_more",
        ),
    ]

    operations = []
